// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPs1M52lYdxssymXhX9JYyLi_USPDLB5o',
    appId: '1:344814689425:web:c2068b135985a2f36c7330',
    messagingSenderId: '344814689425',
    projectId: 'petzify-erp',
    authDomain: 'petzify-erp.firebaseapp.com',
    storageBucket: 'petzify-erp.firebasestorage.app',
    measurementId: 'G-KFCSTF5WMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp2eIn-_XIAB-_2FKWgOwm0IBv0Sbcsjw',
    appId: '1:344814689425:android:d272fe8da3f3aec66c7330',
    messagingSenderId: '344814689425',
    projectId: 'petzify-erp',
    storageBucket: 'petzify-erp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl4KsCX6ZUqXO72TPMsN-0GpasGKFy3W8',
    appId: '1:344814689425:ios:52a4668c4b70a68a6c7330',
    messagingSenderId: '344814689425',
    projectId: 'petzify-erp',
    storageBucket: 'petzify-erp.firebasestorage.app',
    iosBundleId: 'com.example.pzErpSoftware',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl4KsCX6ZUqXO72TPMsN-0GpasGKFy3W8',
    appId: '1:344814689425:ios:52a4668c4b70a68a6c7330',
    messagingSenderId: '344814689425',
    projectId: 'petzify-erp',
    storageBucket: 'petzify-erp.firebasestorage.app',
    iosBundleId: 'com.example.pzErpSoftware',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPs1M52lYdxssymXhX9JYyLi_USPDLB5o',
    appId: '1:344814689425:web:375a8e7546044db86c7330',
    messagingSenderId: '344814689425',
    projectId: 'petzify-erp',
    authDomain: 'petzify-erp.firebaseapp.com',
    storageBucket: 'petzify-erp.firebasestorage.app',
    measurementId: 'G-1795DNHEWR',
  );
}
